### ISSUE TITLE
Upgrade base Ubuntu version to 16.04

### ISSUE THREAD

**Issue by kou** [rake-compiler/rake-compiler-dock#16]
Is there any plan to upgrade base Ubuntu version to the latest LTS, 16.04?
I want to use CMake 3.x to cross compile related library (libzeromq). Ubuntu 14.04 ships only CMake 2.8.12.

If there is no plan to upgrade base Ubuntu version, please close this issue.

**Comment by larskanis** [comment]
Good point! Ubuntu 14.04 is still used because the old mingw32 package is used for RubyInstaller versions before 2.0. Since these ruby versions are mostly obsolete now, upgrading to 16.04 seems like a good plan.

**Comment by kou** [comment]
Great!

**Comment by larskanis** [comment]
rake-compiler-dock is now based on Ubuntu-16.10, but I noticed you've solved the libzeromq issue differently...

**Comment by kou** [comment]
Thanks!

> you've solved the libzeromq issue differently

Sorry...
