### ISSUE TITLE
Ubuntu 17.04 reached EOL on January 13, 2018

### ISSUE THREAD

**Issue by myokoym** [rake-compiler/rake-compiler-dock#17]
Ubuntu 17.04 (Zesty Zapus) reached End of Life on January 13, 2018.

[Ubuntu Fridge | Ubuntu 17.04 (Zesty Zapus) reached End of Life on January 13, 2018](http://fridge.ubuntu.com/2018/01/17/ubuntu-17-04-zesty-zapus-reached-end-of-life-on-january-13-2018/)

Is there any plan to upgrade base Ubuntu version to 17.10?
It seems that some packages have already ended Ubuntu 17.04 support.

**Comment by larskanis** [comment]
I plan to upgrade directly to 18.04. It will probably ship an upgraded gcc version with built-in retpoline capability, so that rake-compiler-dock generates Spectre secured binaries.

Is there a particular vulnerability you worry about, which could affect rake-compiler-dock?

**Comment by myokoym** [comment]
Okay, no problem for me. I thought that it would affect my project, but it was my misunderstanding.
Thank you for your response.
