### ISSUE TITLE
How to use gnu11

### ISSUE THREAD

**Issue by TeBoring** [rake-compiler/rake-compiler-dock#24]
Our code currently depend on strptime which is only provided by posix.
How to use -std=gnu11 in Rakefile?
Thanks!

**Comment by TeBoring** [comment]
https://stackoverflow.com/questions/43460876/trouble-including-function-declaration-for-strptime?rq=1
Some context

**Comment by TeBoring** [comment]
I tried to set CFLAGS in extconf.rb, but didn't work.
How to set it it Rakefile?

**Comment by larskanis** [comment]
CFLAGS can be set in the Rakefile like so:
```ruby
RakeCompilerDock.sh "bundle --local && rake cross native gem CFLAGS=-std=gnu11" 
```
But if it doesn't work in extconf.rb per $CFLAGS, there's probably something other wrong.

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/pull/5660

**Comment by TeBoring** [comment]
Still doesn't work

**Comment by TeBoring** [comment]
Are you able to build an extension which uses strptime?

**Comment by TeBoring** [comment]
Is that related to cross compiling?

**Comment by TeBoring** [comment]
Seems only fail with x86-mingw32.

**Comment by TeBoring** [comment]
ok, seems mingw doesn't have strptime.

**Comment by larskanis** [comment]
MINGW has some small POSIX additions, but isn't really POSIX compliant. Makes sense!
