### ISSUE TITLE
Container isn't compatible with older Ubuntu versions

### ISSUE THREAD

**Issue by jarro2783** [rake-compiler/rake-compiler-dock#25]
Since the upgrade to Ubuntu 18.04 in 560dbf2c18269179449b681ca5d7933f96626f4d, any libraries built by this container are generally not compatible with Ubuntu versions < 18.04. Specifically I'm trying to build `ruby-augeas`, and it uses the `glob` function from libc. The symbol version was bumped in the libc that 18.04 uses, and so the augeas library built with this container doesn't load libc on older Ubuntu versions.

I built this container successfully myself changing the base image back to 17.10. Would you consider changing it back so that built libraries are compatible with more distributions? The change in symbol version is forwards compatible, in that libraries linked to older libc still work on with the newer version.

**Comment by larskanis** [comment]
Only libraries that make use of newer glibc function versions are incompatible. So it depends on the particular library to which glibc version it is compatible to. Using an older Ubuntu version as base image has the downside that newer tools and features aren't available.

However there's a way to force older glibc function versions as described here: https://stackoverflow.com/a/5977518 Can you try to add this to `ruby-augeas`?

In nokogiri we have a [verify function](https://github.com/larskanis/nokogiri/blob/linux-binary-gems/Rakefile#L315-L349) that makes use of `objdump` to ensure compatibility with older OS versions.

**Comment by jarro2783** [comment]
We've tried that. I think the problem is that it's actually in some dependency, and the problem is caused by static linking, and we would need to find the file that actually calls the offending function. The `ruby-augeas` build is abstracted away with `mkmf` and we ended up going down a giant rabbit hole trying to get anything to work, including linking against an older glibc.
For now the simplest solution for us is that we've built this container with 17.10.

**Comment by jarro2783** [comment]
Thanks.

**Comment by jarro2783** [comment]
It looks like one of the Ruby versions doesn't compile on Ubuntu 16.04, but the output is such a mess that I can't work out which one is broken. The end of the error looks like this:
```
	from /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:1156:in `latest_specs'
	from /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:556:in `find_latest_files'
	from /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:19:in `load_executable_plugins'
	from /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:48:in `run'
	from /usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:10:in `<main>'
```

**Comment by larskanis** [comment]
Are you talking about the image build (`rake build` or `docker build`) or about building a gem? I verified with nokogiri, that the gem compiles successfully on all 20 supported ruby versions.

**Comment by jarro2783** [comment]
This was building the image with `Dockerfile.mri`. I can't reproduce it though. I ran it again and it was fine.
