### ISSUE TITLE
Manylinux2010-based Linux docker image

### ISSUE THREAD

**Issue by veblush** [rake-compiler/rake-compiler-dock#33]
How about updating rake-compiler-dock images base on [manylinux2010](https://www.python.org/dev/peps/pep-0571/)? This is pretty useful to cover CentOS 6 or later and other conservative Linux distributions. Manylinux was designed to make sure python extension modules run on most active Linux distribution by using the most oldest one.

Benefits of using Manylinux2010 docker images are: i) Built artifacts can run over as many linux distributions as possible and ii) pretty recent gcc/g++ (gcc 7 for x86 and 8 for x64) are available in the docker images.  

This can be applied to Ruby as well so we can support more Linux distributions without tricky problems with dependency. gRPC recently was starting to have more C++ features and [this hack](https://github.com/rake-compiler/rake-compiler-dock/blob/5dacab741e04354107bc2fa51ed2b5f06aec422e/Dockerfile.mri.erb#L151) wasn't enough. So I'm now thinking of updating it from using Debian to Manylinux (CentOS). 

[This](https://gist.github.com/veblush/9f83ae8bf4fe48af7f665fc49cdd2e5b) is a draft version and it's not verified yet to build them successfully but the docker image itself is verified to be consumed by Docker. (Because of the difference between CentOS and Debian, there are a few things that are non-trivial to translate.) 

What do you think?

**Comment by flavorjones** [comment]
@larskanis I think this can be closed now that you've updated to manylinux2014 in 8e85ee8cd8a9a0ffe586c5232403a340d911fd7d and 352202124a28153cbb88bd28b4db4547df79a6b5

**Comment by veblush** [comment]
Yeah, closing this.
