### ISSUE TITLE
apt-get: command not found with x86_64-linux image

### ISSUE THREAD

**Issue by ankane** [rake-compiler/rake-compiler-dock#43]
Hi, thanks for this great project!

I'm trying to install additional packages on the `x86_64-linux` image, but it looks like `apt-get` is not available. I've noticed `yum` works. Is this expected? If so, I can submit a PR to update the docs.

I also noticed there are images for `x86_64-darwin` and `arm64-darwin`, which it looks like Nokogiri is successfully using. Happy to update the docs for that as well if it's now supported.

Edit: It looks like `apt-get` works on the Windows and Darwin images.

**Comment by ankane** [comment]
Looks like it's a result of https://github.com/rake-compiler/rake-compiler-dock/commit/8e85ee8cd8a9a0ffe586c5232403a340d911fd7d (should have checked the Dockerfile first). Will submit a PR for the docs.

**Comment by larskanis** [comment]
I'm not entirely happy with the solution to use distinct operation systems for the images. Possibly I'll revert to Ubuntu, if I find a way to integrate the manylinux build tools there.

May I ask which packages you need to install?

**Comment by ankane** [comment]
I was installing Git for gems, but the `bundle package`/`bundle --local` approach is probably better.
