### ISSUE TITLE
docker installed but docker not installed error comes up

### ISSUE THREAD

**Issue by benkoshy** [rake-compiler/rake-compiler-dock#46]
## Steps taken:

1. Follow docker installation instructions here: https://docs.docker.com/engine/install/ubuntu/
2. Run docker hello world. `sudo docker run hello-world` the following output is produced:

> Hello from Docker!
> This message shows that your installation appears to be working correctly.

3. cd into my gem file - in my case, this is the `rmagic` cloned repository directory: 

```terminal
~/Documents/www/OpenSourceProjects/rmagick
```

4. Run the command:

```terminal
koshy@koshy-System-Product-Name:~/Documents/www/OpenSourceProjects/rmagick$  rake-compiler-dock
```

And the following error pops up:

```terminal
Neither Docker nor Podman is available.

Install Docker on Ubuntu/Debian:
    sudo apt-get install docker.io

Install Docker on Fedora/Centos/RHEL
    sudo yum install docker
    sudo systemctl start docker

Install Docker on SuSE
    sudo zypper install docker
    sudo systemctl start docker
```

## Expected Result:
* The docker hello world runs successfully - I would expect an error message not to appear.

Please let me know if you require further information.

**Comment by larskanis** [comment]
Rake-compiler-dock checks docker per `docker version`, so it seems that this command fails. On Ubuntu it's necessary to add the running user to group `docker` . Otherwise docker fails with a permission error.

**Comment by benkoshy** [comment]
@larskanis Thank you Lars, I appreciate the comment. I will try this out - if succesfull will make a PR to document this.

**Comment by benkoshy** [comment]
I have added the user: `koshy` to the `docker` group.

`getent group docker` delivers the following response:

`docker:x:990:koshy`

However when I run:

`koshy@koshy-System-Product-Name:~/Documents/www/OpenSourceProjects/rmagick$  rake-compiler-dock`

The following still comes up:

```terminal
Neither Docker nor Podman is available.

Install Docker on Ubuntu/Debian:
    sudo apt-get install docker.io

Install Docker on Fedora/Centos/RHEL
    sudo yum install docker
    sudo systemctl start docker

Install Docker on SuSE
    sudo zypper install docker
    sudo systemctl start docker
```

**Comment by sutharsentio** [comment]
I am also facing the same issue. Please help @larskanis

**Comment by flavorjones** [comment]
@benkoshy @sutharsentio can you please past the output from `docker version` as well as whether that command exits with a 0 (successful) exit code?

**Comment by benkoshy** [comment]
Hey Mike, appreciate the support.

This was from a while ago. I would close the issue from my view point, but I suspect Amit @sutharsentio might want to pursue this?
