### ISSUE TITLE
Add support for "arm64-linux" environment.

### ISSUE THREAD

**Issue by jtattermusch** [rake-compiler/rake-compiler-dock#47]
Currently crosscompiling for linux aarch64 (ARM64) is not supported.

https://github.com/rake-compiler/rake-compiler-dock/blob/427d5a26807bd04b6133a7d62de9d9a992427622/Rakefile#L12

This seems strange, since e.g. "arm64-darwin" is supported and IMHO that's a more complicated setup than arm64 linux, where docker can be utilized to provide the necessary crosscompilation toolchain.

We'd need this for gRPC and protobuf to be able to provide arm64 linux native gems.
https://github.com/grpc/grpc/issues/26391

**Comment by larskanis** [comment]
Yes, support for "arm" and "aarch64" would be nice. "arm64-darwin" was just a waste product of adding support for "x86_64-darwin".

I'm just a bit worried about the different arm architectures, so that I didn't put any efforts on the arm environment. I've seen `ruby -v` responding with `armv6l-linux-eabihf`, `armv7l-linux-eabihf`, `armv5tejl-linux-eabi` and `arm-linux-gnueabihf`. Termux on my Android device reports `arm-linux-androideabi-android` and `gem env` shows platform `arm-linux` there.

**Comment by jtattermusch** [comment]
@larskanis  yes, there are many arm architectures, but I think in terms of 64-bit arm, the world is fairly united. arm64 (also sometimes referred to as aarch64, arm64v8 or armv8) seems to be the universal standard there. arm64 is also the architecture that currently has by far the biggest momentum and its importance has recently risen very significantly, so adding support for crosscompiling arm64 linux native gems would certainly make a lot of sense (even if support for other architectures doesn't get added - all the architectures you mentioned are 32bit arm).

For ruby, the architecture we want is reported by ruby as `aarch64-linux`

`ruby -v` on my linux ARM64 machine gives me this:
```
ruby -v
ruby 2.7.0dev (2019-12-25 master e1e1d92277) [aarch64-linux]
```

The official ruby docker image for ARM64 is here: https://hub.docker.com/r/arm64v8/ruby. Running `docker run -it arm64v8/ruby bash -c 'ruby -v'` also responds with `aarch64-linux`.


A related blogpost (ruby native gems is one of our gaps there): https://grpc.io/blog/grpc-on-arm64/

**Comment by lizthegrey** [comment]
with Ampere being on Packet and Oracle, and Graviton2 being on Amazon, plus pinebook64, solidrun honeycomb, and raspberry pi 4 all being armv8/aarch64/arm64, you can basically ignore armv7 and lower

**Comment by flavorjones** [comment]
Please note that #54 implementing aarch64-linux support was merged.

**Comment by larskanis** [comment]
rake-compiler-dock-1.2.0 adds support for ruby platforms `arm-linux`, `aarch64-linux` and `x64-mingw-ucrt`.
