### ISSUE TITLE
boot2docker deprecated, switch to Docker Toolbox?

### ISSUE THREAD

**Issue by copiousfreetime** [rake-compiler/rake-compiler-dock#5]
It looks like boot2docker is officially deprecated
```
% rake-compiler-dock

boot2docker is available, but not ready to use. Trying to start.

  WARNING: The 'boot2docker' command line interface is officially deprecated.

  Please switch to Docker Machine (https://docs.docker.com/machine/) ASAP.

  Docker Toolbox (https://docker.com/toolbox) is the recommended install method.
```

**Comment by larskanis** [comment]
@copiousfreetime Thank you for the hint! I already did some experimentation with docker-machine, but boot2docker was more simple to use. Now that there is the new docker-toolbox, I'll integrate it into rake-compiler-dock.

However did rake-compiler-dock work for you, so far?

**Comment by copiousfreetime** [comment]
@larskanis A complete lifesaver. Thanks so much. Was finally able to ship a long-overdue new fat binary version of hitimes out last night.

It may be a pretty simple transition -- there looks to be pretty extensive migration docs http://docs.docker.com/installation/mac/#migrate-from-boot2docker

**Comment by larskanis** [comment]
Just as a note: Rake-compiler-dock is typically used as a rake task as described [here](https://github.com/rake-compiler/rake-compiler-dock#add-to-your-rakefile) . The interactive shell is more intended for test and debug...

**Comment by copiousfreetime** [comment]
That's good to know, I missed that bit :-).

**Comment by larskanis** [comment]
Support for docker-machine is now on master.
