### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by j-manu** [rake-compiler/rake-compiler-dock#58]
GRPC is waiting on a release with aarch64-linux support (https://github.com/rake-compiler/rake-compiler-dock/pull/54)
https://github.com/grpc/grpc/issues/26391

Since GRPC gem is used by google-cloud gems there are quite a few people waiting for GRPC support for aarch64 which is blocked on new release of rake-compiler-dock

Please consider making a new release.

**Comment by larskanis** [comment]
I plan to cut a new release with cross compile support of ruby-2.4 to 3.1 today or tomorrow. I found a linker issue in fxruby with `vsscanf()` on `x64-mingw-ucrt` and have a move from Centos back to Ubuntu for the Linux images in the pipeline, but I think it's better to have something working than waiting any longer.

**Comment by larskanis** [comment]
rake-compiler-dock-1.2.0 is released.

**Comment by flavorjones** [comment]
@larskanis Thank you for everything you've done to ship the Ruby 3.1 toolchain!
