### ISSUE TITLE
typo in docker image name for arm64_darwin

### ISSUE THREAD

**Issue by ag-303** [rake-compiler/rake-compiler-dock#62]
I tried to run the arm64 container with this:
```
RCD_PLATFORM=arm64_darwin rake-compiler-dock
```
but it shows:
```
Unable to find image 'larskanis/rake-compiler-dock-mri-arm64_darwin:1.2.0' locally
docker: Error response from daemon: pull access denied for larskanis/rake-compiler-dock-mri-arm64_darwin, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

I looked up the image name it's `larskanis/rake-compiler-dock-mri-arm64-darwin`
when I tried the command with this `RCD_PLATFORM=arm64-darwin rake-compiler-dock` it responded:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
To run a command as administrator (user "root"), use "sudo <command>".
```

**Comment by flavorjones** [comment]
Hi, @ag-303. I don't think there's a typo here, the name of the platform is `arm64-darwin` with a `-` not a `_`.

Although you may get a warning from docker, that shouldn't prevent everything from working. What are you trying to use rake-compiler-dock for, and is there a functional problem that you see?
