### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by Maaarcocr** [rake-compiler/rake-compiler-dock#66]
I'm not sure if I could help with a new release, but my PR in https://github.com/protocolbuffers/protobuf/pull/9566 is currently blocked, as version 1.2.0 has the issue that was solved in https://github.com/rake-compiler/rake-compiler-dock/pull/64

**Comment by JasonLunn** [comment]
Any update on a release, @larskanis ?

**Comment by larskanis** [comment]
I'm working on it.

**Comment by larskanis** [comment]
rake-compiler-dock-1.2.1 is released fixing the above issue among others.
