### ISSUE TITLE
please make the rake-compiler-dock-snapshot package public

### ISSUE THREAD

**Issue by flavorjones** [rake-compiler/rake-compiler-dock#85]
@larskanis @kou Can you please go to https://github.com/orgs/rake-compiler/packages/container/rake-compiler-dock-snapshot/settings and make that package public? That will allow me to integration test rake-compiler 1.2.1 and rake-compiler-dock HEAD with Nokogiri.

I don't have the privileges to make it public. Thank you!

Context:
- pipeline to generate those snapshot images is https://github.com/rake-compiler/rake-compiler-dock/actions/workflows/publish-images.yml
- PR at Nokogiri trying to use these images is https://github.com/sparklemotion/nokogiri/pull/2732

**Comment by kou** [comment]
Done!

**Comment by flavorjones** [comment]
Thank you!
